/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { datasetsGetDatasets } from "../../funcs/datasetsGetDatasets.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$datasetsGetDatasets: ToolDefinition = {
  name: "datasets-get-datasets",
  description: `Get a list of all premium and standard datasets

Returns a list of all datasets. Datasets are collections of features grouped by interest, relevance, commodity, and/or asset class.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await datasetsGetDatasets(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
