/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpOnlyGetFuturesPricesLlmV1AssetsFuturesPricesSymbolLlmGet } from "../../funcs/mcpOnlyGetFuturesPricesLlmV1AssetsFuturesPricesSymbolLlmGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .GetFuturesPricesLlmV1AssetsFuturesPricesSymbolLlmGetRequest$inboundSchema,
};

export const tool$mcpOnlyGetFuturesPricesLlmV1AssetsFuturesPricesSymbolLlmGet:
  ToolDefinition<typeof args> = {
    name:
      "mcp-only-get-futures-prices-llm-v1-assets-futures-prices-symbol-llm-get",
    description: `Get historical prices for a future

Returns historical price data for a given future symbol in optimized text format.
        Prices are available for all actively traded contracts on each day.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await mcpOnlyGetFuturesPricesLlmV1AssetsFuturesPricesSymbolLlmGet(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
