/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpOnlyGetForexDataLlmCodeLlmGet } from "../../funcs/mcpOnlyGetForexDataLlmCodeLlmGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetForexDataLlmCodeLlmGetRequest$inboundSchema,
};

export const tool$mcpOnlyGetForexDataLlmCodeLlmGet: ToolDefinition<
  typeof args
> = {
  name: "mcp-only-get-forex-data-llm-code-llm-get",
  description: `Get forex data for one currency

Returns forex price history for a given currency code in optimized text format.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await mcpOnlyGetForexDataLlmCodeLlmGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
