/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsGetCategories } from "../funcs/assetsGetCategories.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Assets extends ClientSDK {
  /**
   * List available asset categories (e.g. Futures)
   *
   * @remarks
   * Returns a list of all available asset categories, such as
   *         futures. Prices, forecasts, and indicators are available for each.
   */
  async getCategories(
    options?: RequestOptions,
  ): Promise<components.GetAvailableAssetCategoriesResponse> {
    return unwrapAsync(assetsGetCategories(
      this,
      options,
    ));
  }
}
