/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataGetMetadata } from "../funcs/dataGetMetadata.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Data extends ClientSDK {
  /**
   * Get metadata and most recent prices
   *
   * @remarks
   * Returns a list of all asset classes, assets, and currently
   *         active contracts tracked by Hedgewise, as well as their prices from
   *         the prior trading day. Used to build the table on the Hedgewise
   *         landing page.
   */
  async getMetadata(
    options?: RequestOptions,
  ): Promise<components.GetDataResponse> {
    return unwrapAsync(dataGetMetadata(
      this,
      options,
    ));
  }
}
