/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { forexGetPrices } from "../funcs/forexGetPrices.js";
import { forexListPrices } from "../funcs/forexListPrices.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Forex extends ClientSDK {
  /**
   * Get most recent forex prices for all currencies
   *
   * @remarks
   * Get most recent forex prices for all currencies
   */
  async listPrices(
    options?: RequestOptions,
  ): Promise<components.GetAllForexDataResponse> {
    return unwrapAsync(forexListPrices(
      this,
      options,
    ));
  }

  /**
   * Get forex data for one currency
   *
   * @remarks
   * Returns forex price history for a given currency code.
   */
  async getPrices(
    request: operations.GetForexPricesRequest,
    options?: RequestOptions,
  ): Promise<components.GetForexDataResponse> {
    return unwrapAsync(forexGetPrices(
      this,
      request,
      options,
    ));
  }
}
