/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indicatorsList } from "../funcs/indicatorsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Indicators extends ClientSDK {
  /**
   * List available indicators
   *
   * @remarks
   * Returns the list of all available market indicators that
   *         Hedgewise tracks or produces.
   */
  async list(
    options?: RequestOptions,
  ): Promise<components.GetAvailableIndicatorsResponse> {
    return unwrapAsync(indicatorsList(
      this,
      options,
    ));
  }
}
