/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Assets } from "./assets.js";
import { Data } from "./data.js";
import { Features } from "./features.js";
import { Forex } from "./forex.js";
import { Futures } from "./futures.js";
import { Indicators } from "./indicators.js";
import { PerformanceMetrics } from "./performancemetrics.js";
import { SectorIndices } from "./sectorindices.js";
import { Supply } from "./supply.js";
import { System } from "./system.js";

export class Hedgewise extends ClientSDK {
  private _system?: System;
  get system(): System {
    return (this._system ??= new System(this._options));
  }

  private _data?: Data;
  get data(): Data {
    return (this._data ??= new Data(this._options));
  }

  private _assets?: Assets;
  get assets(): Assets {
    return (this._assets ??= new Assets(this._options));
  }

  private _futures?: Futures;
  get futures(): Futures {
    return (this._futures ??= new Futures(this._options));
  }

  private _indicators?: Indicators;
  get indicators(): Indicators {
    return (this._indicators ??= new Indicators(this._options));
  }

  private _forex?: Forex;
  get forex(): Forex {
    return (this._forex ??= new Forex(this._options));
  }

  private _features?: Features;
  get features(): Features {
    return (this._features ??= new Features(this._options));
  }

  private _sectorIndices?: SectorIndices;
  get sectorIndices(): SectorIndices {
    return (this._sectorIndices ??= new SectorIndices(this._options));
  }

  private _performanceMetrics?: PerformanceMetrics;
  get performanceMetrics(): PerformanceMetrics {
    return (this._performanceMetrics ??= new PerformanceMetrics(this._options));
  }

  private _supply?: Supply;
  get supply(): Supply {
    return (this._supply ??= new Supply(this._options));
  }
}
