/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sectorIndicesGet } from "../funcs/sectorIndicesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SectorIndices extends ClientSDK {
  /**
   * Get the proprietary value of the sector index requested
   *
   * @remarks
   * Return the selected sector or asset class index historical values using a proprietary methodology and composition
   */
  async get(
    request: operations.GetAssetClassIndexRequest,
    options?: RequestOptions,
  ): Promise<components.GetSectorIndexHistoricalResponse> {
    return unwrapAsync(sectorIndicesGet(
      this,
      request,
      options,
    ));
  }
}
