/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { supplyGet } from "../funcs/supplyGet.js";
import { supplyListCommodities } from "../funcs/supplyListCommodities.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Supply extends ClientSDK {
  /**
   * List commodities with supply models
   *
   * @remarks
   * Returns a list of all commodities that have supply models
   *         available. Country codes follow the UN/LOCODE standard:
   *         https://unece.org/trade/cefact/unlocode-code-list-country-and-territory
   */
  async listCommodities(
    options?: RequestOptions,
  ): Promise<components.GetAvailableSupplyCommoditiesResponse> {
    return unwrapAsync(supplyListCommodities(
      this,
      options,
    ));
  }

  /**
   * Get supply data for a commodity and country
   *
   * @remarks
   * Returns historical and forecasted supply data for a given
   *         commodity and country. Country codes follow the UN/LOCODE standard:
   *         https://unece.org/trade/cefact/unlocode-code-list-country-and-territory
   */
  async get(
    request: operations.GetSupplyRequest,
    options?: RequestOptions,
  ): Promise<components.GetSupplyResponse> {
    return unwrapAsync(supplyGet(
      this,
      request,
      options,
    ));
  }
}
