/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the hedgewise SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx postFuturesForecasts.ts
 */

import { Hedgewise } from "hedgewise";

const hedgewise = new Hedgewise({
  serverURL: "https://api.example.com",
  bearerAuth: process.env["HEDGEWISE_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await hedgewise.postFuturesForecasts({
    symbol: "ZC",
    postAssetForecastsRequest: {
      strategy: [
        {
          startDate: "2025-04-24",
          endDate: "2025-04-24",
          trajectory: [],
        },
      ],
    },
  });

  console.log(result);
}

main().catch(console.error);
