/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetForexDataLlmCodeLlmGetRequest = {
  /**
   * Three-letter currency code
   */
  code: string;
  /**
   * Start of forex data window (YYYY-MM-DD)
   */
  startDate?: RFCDate | null | undefined;
  /**
   * End of forex data window (YYYY-MM-DD)
   */
  endDate?: RFCDate | null | undefined;
  /**
   * Return prices as foreign currency per USD. If false, prices will be returned as USD per foreign currency.
   */
  foreignPerUsd?: boolean | undefined;
};

/** @internal */
export const GetForexDataLlmCodeLlmGetRequest$inboundSchema: z.ZodType<
  GetForexDataLlmCodeLlmGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  start_date: z.nullable(z.string().transform(v => new RFCDate(v))).optional(),
  end_date: z.nullable(z.string().transform(v => new RFCDate(v))).optional(),
  foreign_per_usd: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    "start_date": "startDate",
    "end_date": "endDate",
    "foreign_per_usd": "foreignPerUsd",
  });
});

/** @internal */
export type GetForexDataLlmCodeLlmGetRequest$Outbound = {
  code: string;
  start_date?: string | null | undefined;
  end_date?: string | null | undefined;
  foreign_per_usd: boolean;
};

/** @internal */
export const GetForexDataLlmCodeLlmGetRequest$outboundSchema: z.ZodType<
  GetForexDataLlmCodeLlmGetRequest$Outbound,
  z.ZodTypeDef,
  GetForexDataLlmCodeLlmGetRequest
> = z.object({
  code: z.string(),
  startDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
    .optional(),
  endDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
    .optional(),
  foreignPerUsd: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    startDate: "start_date",
    endDate: "end_date",
    foreignPerUsd: "foreign_per_usd",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetForexDataLlmCodeLlmGetRequest$ {
  /** @deprecated use `GetForexDataLlmCodeLlmGetRequest$inboundSchema` instead. */
  export const inboundSchema = GetForexDataLlmCodeLlmGetRequest$inboundSchema;
  /** @deprecated use `GetForexDataLlmCodeLlmGetRequest$outboundSchema` instead. */
  export const outboundSchema = GetForexDataLlmCodeLlmGetRequest$outboundSchema;
  /** @deprecated use `GetForexDataLlmCodeLlmGetRequest$Outbound` instead. */
  export type Outbound = GetForexDataLlmCodeLlmGetRequest$Outbound;
}

export function getForexDataLlmCodeLlmGetRequestToJSON(
  getForexDataLlmCodeLlmGetRequest: GetForexDataLlmCodeLlmGetRequest,
): string {
  return JSON.stringify(
    GetForexDataLlmCodeLlmGetRequest$outboundSchema.parse(
      getForexDataLlmCodeLlmGetRequest,
    ),
  );
}

export function getForexDataLlmCodeLlmGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetForexDataLlmCodeLlmGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetForexDataLlmCodeLlmGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetForexDataLlmCodeLlmGetRequest' from JSON`,
  );
}
