/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AssetForecastModelData = {
  modelName: string;
  startDate: RFCDate;
  endDate: RFCDate;
  horizons: Array<number>;
  targetType?: string | null | undefined;
  rollingMeanWindows?: Array<number> | null | undefined;
  features?: Array<string> | null | undefined;
};

/** @internal */
export const AssetForecastModelData$inboundSchema: z.ZodType<
  AssetForecastModelData,
  z.ZodTypeDef,
  unknown
> = z.object({
  model_name: z.string(),
  start_date: z.string().transform(v => new RFCDate(v)),
  end_date: z.string().transform(v => new RFCDate(v)),
  horizons: z.array(z.number().int()),
  target_type: z.nullable(z.string()).optional(),
  rolling_mean_windows: z.nullable(z.array(z.number().int())).optional(),
  features: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "model_name": "modelName",
    "start_date": "startDate",
    "end_date": "endDate",
    "target_type": "targetType",
    "rolling_mean_windows": "rollingMeanWindows",
  });
});

/** @internal */
export type AssetForecastModelData$Outbound = {
  model_name: string;
  start_date: string;
  end_date: string;
  horizons: Array<number>;
  target_type?: string | null | undefined;
  rolling_mean_windows?: Array<number> | null | undefined;
  features?: Array<string> | null | undefined;
};

/** @internal */
export const AssetForecastModelData$outboundSchema: z.ZodType<
  AssetForecastModelData$Outbound,
  z.ZodTypeDef,
  AssetForecastModelData
> = z.object({
  modelName: z.string(),
  startDate: z.instanceof(RFCDate).transform(v => v.toString()),
  endDate: z.instanceof(RFCDate).transform(v => v.toString()),
  horizons: z.array(z.number().int()),
  targetType: z.nullable(z.string()).optional(),
  rollingMeanWindows: z.nullable(z.array(z.number().int())).optional(),
  features: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    modelName: "model_name",
    startDate: "start_date",
    endDate: "end_date",
    targetType: "target_type",
    rollingMeanWindows: "rolling_mean_windows",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AssetForecastModelData$ {
  /** @deprecated use `AssetForecastModelData$inboundSchema` instead. */
  export const inboundSchema = AssetForecastModelData$inboundSchema;
  /** @deprecated use `AssetForecastModelData$outboundSchema` instead. */
  export const outboundSchema = AssetForecastModelData$outboundSchema;
  /** @deprecated use `AssetForecastModelData$Outbound` instead. */
  export type Outbound = AssetForecastModelData$Outbound;
}

export function assetForecastModelDataToJSON(
  assetForecastModelData: AssetForecastModelData,
): string {
  return JSON.stringify(
    AssetForecastModelData$outboundSchema.parse(assetForecastModelData),
  );
}

export function assetForecastModelDataFromJSON(
  jsonString: string,
): SafeParseResult<AssetForecastModelData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssetForecastModelData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssetForecastModelData' from JSON`,
  );
}
