/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum for dataset types.
 */
export const DatasetType = {
  Standard: "standard",
  Premium: "premium",
} as const;
/**
 * Enum for dataset types.
 */
export type DatasetType = ClosedEnum<typeof DatasetType>;

/** @internal */
export const DatasetType$inboundSchema: z.ZodNativeEnum<typeof DatasetType> = z
  .nativeEnum(DatasetType);

/** @internal */
export const DatasetType$outboundSchema: z.ZodNativeEnum<typeof DatasetType> =
  DatasetType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatasetType$ {
  /** @deprecated use `DatasetType$inboundSchema` instead. */
  export const inboundSchema = DatasetType$inboundSchema;
  /** @deprecated use `DatasetType$outboundSchema` instead. */
  export const outboundSchema = DatasetType$outboundSchema;
}
