/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AssetForecastData,
  AssetForecastData$inboundSchema,
  AssetForecastData$Outbound,
  AssetForecastData$outboundSchema,
} from "./assetforecastdata.js";
import {
  AssetForecastSmallData,
  AssetForecastSmallData$inboundSchema,
  AssetForecastSmallData$Outbound,
  AssetForecastSmallData$outboundSchema,
} from "./assetforecastsmalldata.js";

export type GetStrategyForecastResponseData =
  | AssetForecastData
  | AssetForecastSmallData;

export type GetStrategyForecastResponse = {
  success?: true | undefined;
  data: Array<AssetForecastData | AssetForecastSmallData>;
};

/** @internal */
export const GetStrategyForecastResponseData$inboundSchema: z.ZodType<
  GetStrategyForecastResponseData,
  z.ZodTypeDef,
  unknown
> = z.union([
  AssetForecastData$inboundSchema,
  AssetForecastSmallData$inboundSchema,
]);

/** @internal */
export type GetStrategyForecastResponseData$Outbound =
  | AssetForecastData$Outbound
  | AssetForecastSmallData$Outbound;

/** @internal */
export const GetStrategyForecastResponseData$outboundSchema: z.ZodType<
  GetStrategyForecastResponseData$Outbound,
  z.ZodTypeDef,
  GetStrategyForecastResponseData
> = z.union([
  AssetForecastData$outboundSchema,
  AssetForecastSmallData$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStrategyForecastResponseData$ {
  /** @deprecated use `GetStrategyForecastResponseData$inboundSchema` instead. */
  export const inboundSchema = GetStrategyForecastResponseData$inboundSchema;
  /** @deprecated use `GetStrategyForecastResponseData$outboundSchema` instead. */
  export const outboundSchema = GetStrategyForecastResponseData$outboundSchema;
  /** @deprecated use `GetStrategyForecastResponseData$Outbound` instead. */
  export type Outbound = GetStrategyForecastResponseData$Outbound;
}

export function getStrategyForecastResponseDataToJSON(
  getStrategyForecastResponseData: GetStrategyForecastResponseData,
): string {
  return JSON.stringify(
    GetStrategyForecastResponseData$outboundSchema.parse(
      getStrategyForecastResponseData,
    ),
  );
}

export function getStrategyForecastResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<GetStrategyForecastResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStrategyForecastResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStrategyForecastResponseData' from JSON`,
  );
}

/** @internal */
export const GetStrategyForecastResponse$inboundSchema: z.ZodType<
  GetStrategyForecastResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true).default(true).optional(),
  data: z.array(
    z.union([
      AssetForecastData$inboundSchema,
      AssetForecastSmallData$inboundSchema,
    ]),
  ),
});

/** @internal */
export type GetStrategyForecastResponse$Outbound = {
  success: true;
  data: Array<AssetForecastData$Outbound | AssetForecastSmallData$Outbound>;
};

/** @internal */
export const GetStrategyForecastResponse$outboundSchema: z.ZodType<
  GetStrategyForecastResponse$Outbound,
  z.ZodTypeDef,
  GetStrategyForecastResponse
> = z.object({
  success: z.literal(true).default(true as const),
  data: z.array(
    z.union([
      AssetForecastData$outboundSchema,
      AssetForecastSmallData$outboundSchema,
    ]),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStrategyForecastResponse$ {
  /** @deprecated use `GetStrategyForecastResponse$inboundSchema` instead. */
  export const inboundSchema = GetStrategyForecastResponse$inboundSchema;
  /** @deprecated use `GetStrategyForecastResponse$outboundSchema` instead. */
  export const outboundSchema = GetStrategyForecastResponse$outboundSchema;
  /** @deprecated use `GetStrategyForecastResponse$Outbound` instead. */
  export type Outbound = GetStrategyForecastResponse$Outbound;
}

export function getStrategyForecastResponseToJSON(
  getStrategyForecastResponse: GetStrategyForecastResponse,
): string {
  return JSON.stringify(
    GetStrategyForecastResponse$outboundSchema.parse(
      getStrategyForecastResponse,
    ),
  );
}

export function getStrategyForecastResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStrategyForecastResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStrategyForecastResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStrategyForecastResponse' from JSON`,
  );
}
