/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Status = {
  Available: "available",
} as const;
export type Status = ClosedEnum<typeof Status>;

export type PingResponse = {
  status?: "available" | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const PingResponse$inboundSchema: z.ZodType<
  PingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.literal("available").optional(),
});

/** @internal */
export type PingResponse$Outbound = {
  status: "available";
};

/** @internal */
export const PingResponse$outboundSchema: z.ZodType<
  PingResponse$Outbound,
  z.ZodTypeDef,
  PingResponse
> = z.object({
  status: z.literal("available").default("available"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PingResponse$ {
  /** @deprecated use `PingResponse$inboundSchema` instead. */
  export const inboundSchema = PingResponse$inboundSchema;
  /** @deprecated use `PingResponse$outboundSchema` instead. */
  export const outboundSchema = PingResponse$outboundSchema;
  /** @deprecated use `PingResponse$Outbound` instead. */
  export type Outbound = PingResponse$Outbound;
}

export function pingResponseToJSON(pingResponse: PingResponse): string {
  return JSON.stringify(PingResponse$outboundSchema.parse(pingResponse));
}

export function pingResponseFromJSON(
  jsonString: string,
): SafeParseResult<PingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PingResponse' from JSON`,
  );
}
