/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AssetForecastData,
  AssetForecastData$inboundSchema,
  AssetForecastData$Outbound,
  AssetForecastData$outboundSchema,
} from "./assetforecastdata.js";
import {
  AssetForecastSmallData,
  AssetForecastSmallData$inboundSchema,
  AssetForecastSmallData$Outbound,
  AssetForecastSmallData$outboundSchema,
} from "./assetforecastsmalldata.js";

export type PostAssetForecastsResponseData =
  | AssetForecastData
  | AssetForecastSmallData;

export type PostAssetForecastsResponse = {
  success?: true | undefined;
  data: Array<AssetForecastData | AssetForecastSmallData>;
};

/** @internal */
export const PostAssetForecastsResponseData$inboundSchema: z.ZodType<
  PostAssetForecastsResponseData,
  z.ZodTypeDef,
  unknown
> = z.union([
  AssetForecastData$inboundSchema,
  AssetForecastSmallData$inboundSchema,
]);

/** @internal */
export type PostAssetForecastsResponseData$Outbound =
  | AssetForecastData$Outbound
  | AssetForecastSmallData$Outbound;

/** @internal */
export const PostAssetForecastsResponseData$outboundSchema: z.ZodType<
  PostAssetForecastsResponseData$Outbound,
  z.ZodTypeDef,
  PostAssetForecastsResponseData
> = z.union([
  AssetForecastData$outboundSchema,
  AssetForecastSmallData$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAssetForecastsResponseData$ {
  /** @deprecated use `PostAssetForecastsResponseData$inboundSchema` instead. */
  export const inboundSchema = PostAssetForecastsResponseData$inboundSchema;
  /** @deprecated use `PostAssetForecastsResponseData$outboundSchema` instead. */
  export const outboundSchema = PostAssetForecastsResponseData$outboundSchema;
  /** @deprecated use `PostAssetForecastsResponseData$Outbound` instead. */
  export type Outbound = PostAssetForecastsResponseData$Outbound;
}

export function postAssetForecastsResponseDataToJSON(
  postAssetForecastsResponseData: PostAssetForecastsResponseData,
): string {
  return JSON.stringify(
    PostAssetForecastsResponseData$outboundSchema.parse(
      postAssetForecastsResponseData,
    ),
  );
}

export function postAssetForecastsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PostAssetForecastsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostAssetForecastsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAssetForecastsResponseData' from JSON`,
  );
}

/** @internal */
export const PostAssetForecastsResponse$inboundSchema: z.ZodType<
  PostAssetForecastsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.literal(true).default(true).optional(),
  data: z.array(
    z.union([
      AssetForecastData$inboundSchema,
      AssetForecastSmallData$inboundSchema,
    ]),
  ),
});

/** @internal */
export type PostAssetForecastsResponse$Outbound = {
  success: true;
  data: Array<AssetForecastData$Outbound | AssetForecastSmallData$Outbound>;
};

/** @internal */
export const PostAssetForecastsResponse$outboundSchema: z.ZodType<
  PostAssetForecastsResponse$Outbound,
  z.ZodTypeDef,
  PostAssetForecastsResponse
> = z.object({
  success: z.literal(true).default(true as const),
  data: z.array(
    z.union([
      AssetForecastData$outboundSchema,
      AssetForecastSmallData$outboundSchema,
    ]),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostAssetForecastsResponse$ {
  /** @deprecated use `PostAssetForecastsResponse$inboundSchema` instead. */
  export const inboundSchema = PostAssetForecastsResponse$inboundSchema;
  /** @deprecated use `PostAssetForecastsResponse$outboundSchema` instead. */
  export const outboundSchema = PostAssetForecastsResponse$outboundSchema;
  /** @deprecated use `PostAssetForecastsResponse$Outbound` instead. */
  export type Outbound = PostAssetForecastsResponse$Outbound;
}

export function postAssetForecastsResponseToJSON(
  postAssetForecastsResponse: PostAssetForecastsResponse,
): string {
  return JSON.stringify(
    PostAssetForecastsResponse$outboundSchema.parse(postAssetForecastsResponse),
  );
}

export function postAssetForecastsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostAssetForecastsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostAssetForecastsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostAssetForecastsResponse' from JSON`,
  );
}
